# Generated by Django 5.2.7 on 2025-10-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_estudiante_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
