# Generated by Django 5.2.7 on 2025-10-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estudiante_es_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='publicacion',
        ),
        migrations.DeleteModel(
            name='AsignacionReporte',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
