# Generated by Django 5.2.7 on 2025-10-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reporte_administrador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aceptado'), (2, 'Rechazado')], default=0)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.administrador')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionReporte',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.administrador')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reporte')),
            ],
        ),
    ]
