# Generated by Django 5.2.7 on 2025-10-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reporte_asignacionreporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionReporte',
        ),
    ]
