# Generated by Django 5.2.7 on 2025-10-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_asignacionreporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
