# Generated by Django 5.2.7 on 2025-10-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_administrador_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
