# Generated by Django 5.2.7 on 2025-10-31 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_perfil_calificacion_perfil_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='estado',
            new_name='leida',
        ),
        migrations.AddField(
            model_name='chatparticipante',
            name='rol',
            field=models.CharField(choices=[('autor', 'Autor'), ('receptor', 'Receptor')], default='receptor', max_length=20),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.chat'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('nuevo_chat', 'Nuevo chat'), ('nuevo_mensaje', 'Nuevo mensaje'), ('intercambio_completado', 'Intercambio completado'), ('calificacion_recibida', 'Calificación recibida')], default='nuevo_mensaje', max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.publicacion'),
        ),
        migrations.AlterField(
            model_name='chatparticipante',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.chat'),
        ),
        migrations.AlterField(
            model_name='chatparticipante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.chat'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.estudiante'),
        ),
        migrations.CreateModel(
            name='CalificacionChat',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='core.chat')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to='core.estudiante')),
            ],
            options={
                'unique_together': {('chat', 'evaluador')},
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.calificacionchat'),
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
